github:
  description: "Apache Sling Maven Plugin"
  homepage: "https://sling.apache.org/components/sling-maven-plugin/"
  labels:
  - "maven"
  - "bundle"
  - "osgi"
  - "sling"
  - "deploy"
  - "webconsole"
  - "maven-plugin"
  autolink_jira:
  - "SLING"
  - "OAK"
  - "JCR"
  - "JCRVLT"
  - "INFRA"
  - "FELIX"
  - "MNG"
  pull_requests:
    del_branch_on_merge: true
  protected_branches:
    master: {}
notifications:
  jira_options: "link"
  pullrequests_bot_sonarcloud: "commits@sling.apache.org"
