github:
  description: "Apache Sling Maven Plugin"
  homepage: "https://sling.apache.org/components/sling-maven-plugin/"
  labels:
  - "maven"
  - "bundle"
  - "osgi"
  - "sling"
  - "deploy"
  - "webconsole"
  - "maven-plugin"
  autolink_jira:
  - "SLING"
  - "OAK"
  - "JCR"
  - "JCRVLT"
  - "INFRA"
  - "FELIX"
  - "MNG"
notifications:
  jira_options: "link"
